// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passwords.sql

package database

import (
	"context"
)

const checkPassword = `-- name: CheckPassword :one
SELECT hashed_password FROM users WHERE email = $1
`

func (q *Queries) CheckPassword(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, checkPassword, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
