#
#   Creates a new short code.
#   Create On 14/01/2026
#


POST http://localhost:8080/api/validate_chirp


{
    "body": "i don't know what I'm doing"
}

###

POST http://localhost:8080/api/validate_chirp

{
    "body": " lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}   

###
POST http://localhost:8080/api/validate_chirp

{
    "body": "I really need a kerfuffle to go to bed sooner, Fornax !"
}

###
POST http://localhost:8080/api/validate_chirp

{
    "body": "I want a kerfuffle to go to the kitchen sooner, Fornax!"
}

###
POST http://localhost:8080/api/users

{
    "email": "giuseppebloob@gmail.com"
}

###
POST http://localhost:8080/admin/reset

